---
title: "data clean_jy2965"
author: "Jun Yin"
date: "11/22/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
library(rvest)
library(httr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```



## Importing Data

```{r}

squrriel = read_csv("/Users/junyin/Desktop/data science/p8105_final/data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names()  
skimr::skim(squrriel) # observe the distribution of our dataset
```




## Data Cleaning


```{r}
squrriel = read_csv("/Users/junyin/Desktop/data science/p8105_final/data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names() %>% 
mutate(sighter_measurement = as.numeric(above_ground_sighter_measurement))
```