---
title: "map"
author: "xinran"
date: "11/25/2019"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(leaflet)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```



## Importing Data

```{r}

squrriel = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names()  
skimr::skim(squrriel) # observe the distribution of our dataset
```




## Data Cleaning


```{r}
squrriel = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names() %>% 
mutate(sighter_measurement = as.numeric(above_ground_sighter_measurement))%>%
rename(lat=y,
       long=x)
```


## make

```{r}
squrriel %>%
  mutate(text_label=hectare_squirrel_number)%>%
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~hectare_squirrel_number, text = ~text_label, alpha = 0.5)
```

```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain = squrriel$hectare_squirrel_number)

squrriel%>%
  mutate(
    label=hectare_squirrel_number)%>%
  leaflet()%>%
  addTiles()%>%
  addProviderTiles(providers$Esri.NatGeoWorldMap)%>% 
  addCircleMarkers(
    ~lat, ~long,
    radius = 1,
    popup = ~ label)
```



