---
title: "Final_Anran"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)


knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## load in data

```{r}
hectare = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Hectare_Data.csv") %>% 
janitor::clean_names()
skimr::skim(hectare)
```


#### based on hectare, observe the characteristics of squirrels.  
litter, 



## clean the dataset. 

```{r, error = TRUE }
numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
}

hectare = 
  hectare %>% 
  mutate(
      temperature_fahrenheit = numextract(sighter_observed_weather_data),
      temperature_fahrenheit = recode(temperature_fahrenheit, `-50` = "NA"),
      rate = number_of_squirrels/total_time_of_sighting
) %>% 

  ggplot(aes(x = temperature_fahrenheit, y = rate, group = temperature_fahrenheit)) + geom_point()

## numbers for each temperature. (-50 is not temprature.).   to categorize the temperature?????? 

temperature = 
  hectare %>% 
  select(sighter_observed_weather_data, temperature_fahrenheit) %>% 
  na.omit()
  count(temperature, temperature_fahrenheit) %>% view()



levels(as.factor(hectare$temperature_fahrenheit))
levels(as.factor(hectare$litter))  ## Abundant, None, Some. 
levels(as.factor(hectare$hectare_conditions)) # "Busy""Calm""Calm, Busy" "Medium"     "Moderate"  
> 
  
  
  
#################################################
#######################################################


   separate(date, into = c('day','year'), sep = 4) %>% 
   separate(day, into = c('month','date'), sep = 2) %>% 

## sum of the squirrels for each day. 
sum = 
hectare %>% 
  group_by(date) %>% 
  summarise(
    sum = sum(number_of_squirrels)
  )

## weather clean 
clean = 
hectare %>% 
  select(sighter_observed_weather_data) %>% 
  mutate(
    weather = 
        gsub("[^a-zA-Z]", "",hectare$sighter_observed_weather_data)
      ) 

rainy = 
  clean %>% 
  filter(str_detect(weather, "ain")) %>% 
  mutate(
    weather = "Rainy"
  )

sunny = 
  clean %>% 
  filter(str_detect(weather, "un")) %>% 
  mutate(
    weather = "Sunny"
  )

  

levels(as.factor(hectare$sighter_observed_weather_data))

```






## draft for cleaning weather, but error. 

```{r, error = TRUE}
numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
}
 mutate(
     Weather = ifelse(str_detect(sighter_observed_weather_data,c("sun", "Sun")) == "TRUE", "Sunny",
              ifelse(str_detect(sighter_observed_weather_data,c("cloud", "Cloud")) == "TRUE",
 "Cloudy", 
              ifelse(str_detect(sighter_observed_weather_data,c("Windy", "wind")) == "TRUE", "Windy",
                      "Others")))
    ) %>% 
```






 
