---
title: "model"
author: "xinran"
date: "12/2/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
library(rvest)
library(httr)
library(nnet)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```


## Importing Data

```{r, results='hide',message=FALSE}
squrriel = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names()  
skimr::skim(squrriel) # observe the distribution of our dataset
```


## Data Cleaning

```{r,message=FALSE}
squrriel = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names() %>% 
mutate(age_group = ifelse(age %in% "Adult","Adult",ifelse(age %in% "Juvenile","Juvenile","Unknown")),
      age_group = fct_relevel(as.factor(age_group),c("Juvenile","Adult","Unknown")),
      location = fct_relevel(as.factor(location),c("Above Ground","Ground Plane")),
      primary_fur_color = fct_relevel(as.factor(primary_fur_color),c("Cinnamon","Gray","Black"))) %>% 
separate(date,into=c('day','year'),sep=4) %>% 
separate(day,into = c('month','Date'), sep=2) %>% 
mutate(Day = recode(Date, "06"="Day1", "07"="Day2", "08"="Day3", "10"="Day4", "12"="Day5", "13"="Day6", "14"="Day7", "17"="Day8", "18"="Day9", "19"="Day10", "20"="Day11"),
       Day = fct_relevel(Day, c("Day1", "Day2", "Day3", "Day4", "Day5", "Day6", "Day7", "Day8", "Day9", "Day10", "Day11")))%>%
select(-Date,-month, -year)
```

```{r}
hectare_data=read_csv("./data/2018_Central_Park_Squirrel_Census_-_Hectare_Data.csv") %>% 
janitor::clean_names()%>%
separate(date,into=c('day','year'),sep=4) %>% 
separate(day,into = c('month','Date'), sep=2)%>%
mutate(Day = recode(Date, "06"="Day1", "07"="Day2", "08"="Day3", "10"="Day4", "12"="Day5", "13"="Day6", "14"="Day7", "17"="Day8", "18"="Day9", "19"="Day10", "20"="Day11"),
       Day = fct_relevel(Day, c("Day1", "Day2", "Day3", "Day4", "Day5", "Day6", "Day7", "Day8", "Day9", "Day10", "Day11")),
       litter = ifelse(is.na(litter) == TRUE, 'Unknown', litter),
       litter = fct_relevel(as.factor(litter),c("Unknown","None","Some","Abundant")),
       hectare_conditions = ifelse(is.na(hectare_conditions) == TRUE, 'Unknown', hectare_conditions),
       hectare_conditions = fct_relevel(as.factor(hectare_conditions), c("Unknown", "Calm", "Moderate", "Medium","Busy")))%>%
select(-Date,-month, -year)

numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
}

hectare_data = 
  hectare_data %>% 
  mutate(
      temperature = numextract(sighter_observed_weather_data),
      temperature=as.numeric(temperature)
)
```

```{r}
total_data=
  left_join(squrriel, hectare_data, by=c("hectare","Day","shift"))%>%
  mutate(rate = number_of_squirrels/total_time_of_sighting)%>%
  filter(hectare_conditions!="Calm, Busy")
```

$$ Rate \ of \ Squirrel \ Observed \sim \beta_0 + \beta_1 temperature + \beta_2 litterNone + \beta_3 litterSome + \beta_4 litterAbundant + \beta_5 hectare_conditionsCalm +\beta_6 hectare_conditionsModerate +\beta_7 hectare_conditionsMedium +\beta_8 hectare_conditionsBusy + \varepsilon_i,$$


```{r}
linearMod <- lm(rate ~ temperature+litter+hectare_conditions, data=total_data)


linearMod%>%
broom::tidy() %>% 
  select(term, estimate, p.value) %>%
  knitr::kable(digit=3)
```


```{r}
squ_ac=multinom(running+chasing+climbing+eating+foraging~age+litter+temperature,data=total_data)


coef(squ_ac)%>%
broom::tidy() %>% 
  knitr::kable()


```


```{r}
interact=multinom(kuks+quaas+tail_flags+tail_twitches+approaches+indifferent+runs_from~age+litter+temperature,data=total_data)


coef(interact)%>%
broom::tidy()%>%
  knitr::kable()
```



