---
title: "Squirrel Activities"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(patchwork)
library(rvest)
library(httr)
library(plotly)
library(shiny)
```



```{r,message=FALSE}
squrriel = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names()  
```


 
```{r,message=FALSE}
squrriel_plot = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names() %>% 
mutate(age_group = ifelse(age %in% "Adult","Adult",ifelse(age %in% "Juvenile","Juvenile","Unknown")),
      age_group = fct_relevel(as.factor(age_group),c("Juvenile","Adult","Unknown")),
      location = fct_relevel(as.factor(location),c("Above Ground","Ground Plane")),
      primary_fur_color = fct_relevel(as.factor(primary_fur_color),c("Cinnamon","Gray","Black"))) %>% 
separate(date,into=c('day','year'),sep=4) %>% 
separate(day,into = c('month','Date'), sep=2) %>% 
mutate(Day = recode(Date, "06"="Day1", "07"="Day2", "08"="Day3", "10"="Day4", "12"="Day5", "13"="Day6", "14"="Day7", "17"="Day8", "18"="Day9", "19"="Day10", "20"="Day11"),
       Day = fct_relevel(Day, c("Day1", "Day2", "Day3", "Day4", "Day5", "Day6", "Day7", "Day8", "Day9", "Day10", "Day11"))) %>% 
  group_by(Day, age_group) %>% 
  summarise(
    running = sum(running == "TRUE"),
    chasing = sum(chasing == "TRUE"),
    climbing = sum(climbing == "TRUE"),
    eating = sum(eating == "TRUE"),
    approaches = sum(approaches == "TRUE"),
    foraging = sum(foraging == "TRUE"),
    indifferent = sum(indifferent == "TRUE"),
    kuks = sum(kuks == "TRUE"),
    quaas = sum(quaas == "TRUE"),
    runs_from = sum(runs_from == "TRUE"),
    tail_flags = sum(tail_flags == "TRUE"),
    tail_twitches = sum( tail_twitches== "TRUE")
    ) %>% 
    pivot_longer(
    running:tail_twitches,
    names_to = "activity", 
    values_to = "number_of_ture")%>%
  mutate(activity = as.factor(activity))


squrriel_plot_2 = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names() %>% 
mutate(age_group = ifelse(age %in% "Adult","Adult",ifelse(age %in% "Juvenile","Juvenile","Unknown")),
      age_group = fct_relevel(as.factor(age_group),c("Juvenile","Adult","Unknown")),
      location = fct_relevel(as.factor(location),c("Above Ground","Ground Plane")),
      primary_fur_color = fct_relevel(as.factor(primary_fur_color),c("Cinnamon","Gray","Black"))) %>% 
separate(date,into=c('day','year'),sep=4) %>% 
separate(day,into = c('month','Date'), sep=2) %>% 
mutate(Day = recode(Date, "06"="Day1", "07"="Day2", "08"="Day3", "10"="Day4", "12"="Day5", "13"="Day6", "14"="Day7", "17"="Day8", "18"="Day9", "19"="Day10", "20"="Day11"),
       Day = fct_relevel(Day, c("Day1", "Day2", "Day3", "Day4", "Day5", "Day6", "Day7", "Day8", "Day9", "Day10", "Day11"))) %>% 
  group_by(Day) %>% 
  summarise(
    running = sum(running == "TRUE"),
    chasing = sum(chasing == "TRUE"),
    climbing = sum(climbing == "TRUE"),
    eating = sum(eating == "TRUE"),
    approaches = sum(approaches == "TRUE"),
    foraging = sum(foraging == "TRUE"),
    indifferent = sum(indifferent == "TRUE"),
    kuks = sum(kuks == "TRUE"),
    quaas = sum(quaas == "TRUE"),
    runs_from = sum(runs_from == "TRUE"),
    tail_flags = sum(tail_flags == "TRUE"),
    tail_twitches = sum( tail_twitches== "TRUE")
    ) %>% 
    pivot_longer(
    running:tail_twitches,
    names_to = "activity", 
    values_to = "number_of_ture")%>%
  mutate(activity = as.factor(activity))




squrriel_plot_3 = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>%
janitor::clean_names() %>% 
mutate(age_group = ifelse(age %in% "Adult","Adult",ifelse(age %in% "Juvenile","Juvenile","Unknown")),
      age_group = fct_relevel(as.factor(age_group),c("Juvenile","Adult","Unknown")),
      location = fct_relevel(as.factor(location),c("Above Ground","Ground Plane")),
      primary_fur_color = fct_relevel(as.factor(primary_fur_color),c("Cinnamon","Gray","Black"))) %>% 
separate(date,into=c('day','year'),sep=4) %>% 
separate(day,into = c('month','Date'), sep=2) %>% 
mutate(Day = recode(Date, "06"="Day1", "07"="Day2", "08"="Day3", "10"="Day4", "12"="Day5", "13"="Day6", "14"="Day7", "17"="Day8", "18"="Day9", "19"="Day10", "20"="Day11"),
       Day = fct_relevel(Day, c("Day1", "Day2", "Day3", "Day4", "Day5", "Day6", "Day7", "Day8", "Day9", "Day10", "Day11"))) %>% 
  group_by(Day, age_group) %>% 
  summarise(
    running = sum(running == "TRUE"),
    chasing = sum(chasing == "TRUE"),
    climbing = sum(climbing == "TRUE"),
    eating = sum(eating == "TRUE"),
    approaches = sum(approaches == "TRUE"),
    foraging = sum(foraging == "TRUE"),
    indifferent = sum(indifferent == "TRUE"),
    kuks = sum(kuks == "TRUE"),
    quaas = sum(quaas == "TRUE"),
    runs_from = sum(runs_from == "TRUE"),
    tail_flags = sum(tail_flags == "TRUE"),
    tail_twitches = sum( tail_twitches== "TRUE")
    ) %>% 
  mutate(noninteraction = running + chasing + climbing + eating + foraging,
         interaction = kuks + quaas + tail_flags + tail_twitches + indifferent + runs_from) %>% 
  select(Day,age_group, noninteraction, interaction)

```



Column {.sidebar}
-----------------------------------------------------------------------


```{r}
squrriel_activity = squrriel_plot$activity %>% levels()
# selectInput widget
selectInput(
  "Activity", 
  label = h3("Squrriel Activity"),
  choices = squrriel_activity)

age = squrriel_plot$age_group %>% levels()
# selectInput widget
selectInput(
  "Age Group", 
  label = h3("Age Group"),
  choices = age)

days = squrriel_plot_2 %>% distinct(Day)%>%arrange(Day)%>%pull()
# selectInput widget
selectInput(
  "sighting day", 
  label = h3("Select the day"),
  choices = days)


```


Column {data-width=600}
-----------------------------------------------------------------------

### Frequency of Activity Among All Sighting Days

```{r}
renderPlotly({ 
squrriel_plot %>%
  filter(
      activity == input[["Activity"]], 
      age_group == input[["Age Group"]]) %>% 
  mutate(text_label=number_of_ture)%>%
 plot_ly(x = ~Day, y = ~number_of_ture, type = "scatter", mode =  "markers", linetype = I("dash")) %>% 
     layout(
         xaxis = list(title = "Day"),
         yaxis = list(title = "Frequency")
     )
})
   

```



### Distribution of Activity In One Day

```{r}
renderPlotly({ 
squrriel_plot_2 %>%
  filter(
      Day == input[["sighting day"]]) %>% 
plot_ly(labels = ~activity, values = ~number_of_ture) %>%
  add_pie(hole = 0.6) %>%
  layout(
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
})

```


Column {data-width=400}
-----------------------------------------------------------------------
### Frequency of Dichotomized Activity Among All Sighting Day

```{r}
renderPlotly({ 
squrriel_plot_3 %>%
  filter(
      age_group == input[["Age Group"]]) %>% 
 plot_ly(x = ~Day, y = ~interaction, type = 'bar', name = 'Interaction', marker = list(color = 'rgb(149,130,189)')) %>%
  add_trace(y = ~noninteraction, name = 'Noninteraction', marker = list(color = 'rgb(100,100,100)')) %>%
  layout(yaxis = list(title = "Frequency"),
         margin = list(b = 200),
         barmode = 'group') %>% 
    layout(legend = list(x = 0.8, y = 1.2))
})
```

