---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(patchwork)
library(rvest)
library(httr)
library(plotly)
library(shiny)
library(leaflet)
```


```{r,message=FALSE}
squrriel = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names()  
```

 
```{r,message=FALSE}
squrriel = read_csv("./data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv") %>% 
janitor::clean_names() %>% 
mutate(sighter_measurement = as.numeric(above_ground_sighter_measurement),
       age = ifelse(age %in% "Adult","Adult",ifelse(age %in% "Juvenile","Juvenile","Unknown")),
       primary_fur_color = ifelse(is.na(primary_fur_color) == TRUE, 'NA', primary_fur_color))%>%
separate(date,into=c('day','year'),sep=4) %>% 
separate(day,into = c('month','Date'), sep=2) %>% 
separate(hectare,into = c('hec_num','hec_let'), sep=2)%>%
mutate(Day = recode(Date, "06"="Day1", "07"="Day2", "08"="Day3", "10"="Day4", "12"="Day5", "13"="Day6", "14"="Day7", "17"="Day8", "18"="Day9", "19"="Day10", "20"="Day11"),
       Day = fct_relevel(Day, c("Day1", "Day2", "Day3", "Day4", "Day5", "Day6", "Day7", "Day8", "Day9", "Day10", "Day11")))%>%
arrange(hec_num,hec_let)%>%
rename(lat=y,long=x)%>%

select(-month, -year,-color_notes, -specific_location, -other_activities, -other_interactions,-lat_long)
```


Column {.sidebar}
-----------------------------------------------------------------------


```{r}
fur_color = squrriel %>% distinct(primary_fur_color) %>% pull()
# selectInput widget
selectInput(
  "primary fur color", 
  label = h3("Select fur color"),
  choices = fur_color)

days = squrriel %>% distinct(Day)%>%arrange(Day)%>%pull()
# selectInput widget
selectInput(
  "observe day", 
  label = h3("Select the day"),
  choices = days)

```



Column {data-width=1000}
-----------------------------------------------------------------------

### Chart A


```{r}
renderLeaflet({pal=colorNumeric(
  palette = "viridis",
  domain = squrriel$hectare_squirrel_number)

squrriel%>%
  filter(
      primary_fur_color == input[["primary fur color"]], 
      Day == input[["observe day"]]) %>% 
  mutate(
    label = paste0("<strong>hectare squirrel number: </strong> ",
  hectare_squirrel_number))%>%
  leaflet()%>%
  addLegend(pal = pal, values=~hectare_squirrel_number,opacity = 0.5, title = "hectare squirrel number")%>%
  addTiles()%>%
  addProviderTiles(providers$Esri.NatGeoWorldMap)%>% 
  addCircleMarkers(
    ~long, ~lat,
    color=~pal(hectare_squirrel_number),
    radius = 1,
    popup = ~ label)})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({ 
squrriel %>%
  filter(
      primary_fur_color == input[["primary fur color"]], 
      Day == input[["observe day"]]) %>% 
  mutate(
    hectare_squirrel_number=as.integer(hectare_squirrel_number),
    text_label=hectare_squirrel_number)%>%
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~hectare_squirrel_number, text = ~text_label, alpha = 0.5)
})

```

### Chart C

```{r}

```